services:
  app:
    image: course-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coursehub-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/course_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=Klisor
      - SPRING_DATASOURCE_PASSWORD=123456
    depends_on:
      - mysql
    networks:
      - coursehub-network
    restart: unless-stopped

  mysql:
    image: mysql:8  # 使用打标签后的标准名称
    container_name: coursehub-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=course_db
      - MYSQL_USER=Klisor
      - MYSQL_PASSWORD=123456
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - coursehub-network
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

volumes:
  mysql-data:
    driver: local

networks:
  coursehub-network:
    driver: bridge